[build]
base = "example-servers/sveltekit"
command = "npm install --include=dev && npm run build"
publish = "example-servers/sveltekit/.svelte-kit/output/client"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
command = "npm run dev"
port = 3000
publish = "example-servers/sveltekit/.svelte-kit/output/client"
